### ISSUE TITLE
website down.

### ISSUE THREAD

**Issue by oxarbitrage** [jhtitor/citadel#3]
FYI: https://citadel.li/desktop/ seems to be down.

**Comment by alexlobanov** [comment]
@jhtitor I can suggest to use some monitoring software, like apichecker.com. 
And once Site/API will go down - it will alert you via EMAIL or Slack, etc.
And with Public Status pages your customers, like @oxarbitrage and myself will be in loop of your service statuses as well.

**Comment by jhtitor** [comment]
Thanks guys, I'm not the one handling the website, but I have passed that notion along.

Sorry for the downtimes.
